### ISSUE TITLE
update Obsidian function

### ISSUE THREAD

**Issue by gutembergmaciel** [Adiel-kilonzi/jw_webscrape#1]
Hi, tks for code.

I'm looking for a plugin to extract text and include it as a citation in obsidian.
Can you help me with this demand?
As I don't know how to program, I ask for help from someone who does.

**Comment by Adiel-kilonzi** [comment]
Hi @gutembergmaciel,

I am sorry I don't have any experience working with obsidian so I would not be the right person to help you with this task.
